apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nginx
    release: prometheus
spec:
  endpoints:
    - interval: 1s
      path: /metrics
      port: prometheus
  namespaceSelector:
    matchNames:
      - ingress
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-metrics
