apiVersion: v1
kind: Namespace
metadata:
  name: test-postgres
  labels:
    name: test-postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: test-postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: jdevries3133/test-psql-no-hugepages
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: your_database_name
            - name: POSTGRES_USER
              value: your_username
            - name: POSTGRES_PASSWORD
              value: your_password
